yolo.api.url=http://127.0.0.1:5000
server.port=8080

detection.save.path=


spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

logging.logback.rollingpolicy.max-file-size=1000MB